---
- name: Remove previous Obento instalation
  ansible.builtin.file:
    path: /home/ubuntu/obento
    state: absent

- name: Create Obento directory
  ansible.builtin.file:
    path: /home/ubuntu/obento
    owner: ubuntu
    group: ubuntu
    state: directory
    mode: '0755'
  become: no

- name: Get Obento repository and checkout to dev branch
  ansible.builtin.git:
    repo: 'git@github.com:alejandroaizel/obento_api.git'
    accept_hostkey: yes
    dest: /home/ubuntu/obento
    version: dev
  become: no

# TODO to test
- name: Create obento_env
  ansible.builtin.shell:
    chdir: /home/ubuntu/obento
    cmd: "python3 -m venv obento_env"

# TODO to test
- name: Activate obento_env
  ansible.builtin.shell:
    chdir: /home/ubuntu/obento
    cmd: source obento_env/bin/activate

- name: Install pip dependencies
  pip:
    requirements: /home/ubuntu/obento/obento_project/requirements.txt
  args:
    chdir: /home/ubuntu/obento/obento_project

# TODO to test
- name: Run migrations
  make:
    chdir: /home/ubuntu/obento/obento_project
    target: migrate
    file: /home/ubuntu/obento/obento_project/Makefile