# Generated by Django 4.0.3 on 2022-03-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
