# Generated by Django 4.0.3 on 2022-03-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=100)),
                ('unitary_price', models.FloatField()),
                ('kcalories', models.FloatField()),
                ('icon_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('category', models.IntegerField()),
                ('steps', models.CharField(max_length=5000)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_launch', models.BooleanField(default=True)),
                ('image_path', models.CharField(max_length=300)),
                ('total_stars', models.PositiveBigIntegerField(default=0)),
                ('num_scores', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obento_api.ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obento_api.recipe')),
            ],
        ),
    ]
