# Generated by Django 4.0.3 on 2022-03-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
