# Generated by Django 4.0.3 on 2022-03-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0002_remove_compound_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='ingredient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obento_api.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='obento_api.Compound', to='obento_api.ingredient'),
        ),
    ]
