# Generated by Django 4.0.3 on 2022-03-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0003_compound_ingredient_id_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
