# Generated by Django 4.0.3 on 2022-03-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0003_recipe_servings_recipe_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('num_stars', models.FloatField(default=0.0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obento_api.recipe')),
            ],
            options={
                'db_table': 'score',
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
