# Generated by Django 4.0.3 on 2022-03-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0003_recipe_servings_recipe_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obento_api.ingredient')),
            ],
            options={
                'db_table': 'add',
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
