# Generated by Django 4.0.3 on 2022-03-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='compound',
            name='ingredient_id',
            field=models.BigIntegerField(),
        ),
    ]
