# Generated by Django 4.0.3 on 2022-04-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='%Y/04/10'),
        ),
    ]
