# Generated by Django 4.0.3 on 2022-03-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0006_rename_recipe_id_compound_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='ingredient_id',
        ),
        migrations.AddField(
            model_name='compound',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obento_api.ingredient'),
        ),
    ]
