# Generated by Django 4.0.3 on 2022-04-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0006_alter_recipe_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='%Y/04/18'),
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obento_api.ingredient')),
            ],
            options={
                'db_table': 'add',
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
