# Generated by Django 4.0.3 on 2022-03-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obento_api', '0007_remove_compound_ingredient_id_compound_ingredient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
